# Generated by Django 4.1 on 2022-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("company", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=32)),
                ("form_data", models.JSONField()),
            ],
        ),
    ]
